@echo off
setlocal

set "HOST=127.0.0.1"
set "PORT=8000"
set "APP_EXE=%~dp0pdf_matcher.exe"

if not exist "%APP_EXE%" (
	echo Could not find %APP_EXE%
	echo Run this script from the portable folder generated by build_portable.bat.
	exit /b 1
)

set "HOST=%HOST%"
set "PORT=%PORT%"
start "PDF Matcher" "%APP_EXE%"

timeout /t 2 /nobreak >nul
start "" "http://%HOST%:%PORT%/"
